[phases.setup]
nixpkgs = ["openjdk21"]

[phases.build]
cmds = [
  "chmod +x ./mvnw",  # Ensure execute permissions
  "./mvnw clean package -DskipTests"  # Changed from install to package
]

[start]
cmd = "java -jar target/*.jar"  # Changed from spring-boot:run